use_frameworks!

target 'NoodleBoxExample' do

    pod 'NoodleBox', :path => '../'
    #pod 'NoodleBox', :git => ':git => 'https://github.com/NoodleOfDeath/NoodleBox.git'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
