use_frameworks!

target 'NoodleBoxExample' do

    pod 'NoodleBox', :path => '../'
    #pod 'NoodleBox', :git => ':git => 'https://github.com/NoodleOfDeath/NoodleBox.git'
    
    target 'NoodleBoxExample_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 0.8'
        pod 'Nimble', '~> 3.0'
    end

end
