use_frameworks!

target 'NoodleBoxExample' do

    pod 'NoodleBox', :path => '../'
    
    target 'NoodleBoxExample_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 0.8'
        pod 'Nimble', '~> 3.0'
    end

end
